repository:
  name: hugo-geekdoc
  description: Hugo theme made for documentation
  homepage: https://geekdocs.de
  topics: hugo, theme, hugo-theme, documentation

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts:
          - ci/woodpecker/pr/test
          - ci/woodpecker/pr/build-package
          - ci/woodpecker/pr/docs
      enforce_admins: false
      required_linear_history: true
      restrictions: null
