---
depends_on: []
kind: pipeline
name: test
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - npm install > /dev/null
  - npx gulp default
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts
  name: assets
- commands:
  - mkdir exampleSite/themes/ && ln -s $(pwd)/ exampleSite/themes/hugo-geekdoc
  - hugo -s exampleSite/ -b http://localhost/
  image: thegeeklab/hugo:0.83.1
  name: testbuild
- commands:
  - vnu --skip-non-html --also-check-css --errors-only --filterfile .vnuignore exampleSite/public
  image: thegeeklab/vnu
  name: html-validation
- commands:
  - link-validator -ro --exclude "https://github.com/thegeeklab/hugo-geekdoc/edit/main/*"
  environment:
    LINK_VALIDATOR_BASE_DIR: exampleSite/public
  image: thegeeklab/link-validator
  name: link-validation
- commands:
  - lhci autorun
  environment:
    LHCI_SERVER_URL: https://drone-artifact.rknet.org/${DRONE_REPO_NAME}/
  image: thegeeklab/lhci
  name: page-validation
- image: plugins/s3
  name: page-validation-upload
  settings:
    access_key:
      from_secret: s3_access_key
    bucket: drone-artifact
    endpoint: https://sp.rknet.org
    path_style: true
    secret_key:
      from_secret: s3_secret_access_key
    source: lhci_reports/dist/*
    strip_prefix: lhci_reports/dist/
    target: /${DRONE_REPO_NAME}
  when:
    status:
    - failure
    - success
- image: thegeeklab/drone-github-comment
  name: page-validation-link
  settings:
    api_key:
      from_secret: github_token
    key: pr-${DRONE_PULL_REQUEST}
    message: lhci_reports/dist/summary.md
    skip_missing: true
    update: true
  when:
    ref:
    - refs/pull/**
    status:
    - failure
    - success
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
depends_on:
- test
kind: pipeline
name: build
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - npm install > /dev/null
  - npx gulp default
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts
  name: assets
- commands:
  - mkdir dist/
  - echo "${DRONE_TAG:-latest}" > VERSION
  - tar -zcvf dist/hugo-geekdoc.tar.gz -X .tarignore .
  image: thegeeklab/alpine-tools
  name: package
- commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt
  image: thegeeklab/alpine-tools
  name: checksum
- commands:
  - git fetch -tq
  - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
  - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased
    unreleased}
  image: thegeeklab/git-chglog
  name: changelog
- image: plugins/github-release
  name: release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
concurrency:
  limit: 1
depends_on:
- build
kind: pipeline
name: docs
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - markdownlint 'exampleSite/content/**/*.md' 'README.md'
  image: thegeeklab/markdownlint-cli
  name: markdownlint
- commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'exampleSite/content/**/*.md' 'README.md' -d .dictionary
    -p spell indefinite-article syntax-urls frontmatter --frontmatter-keys title --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts-alpine
  name: spellcheck
- commands:
  - npm install > /dev/null
  - npx gulp svg-sprite-list
  - mkdir -p exampleSite/themes/hugo-geekdoc/
  - curl -sSL https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz
    | tar -xz -C exampleSite/themes/hugo-geekdoc/ --strip-components=1
  image: node:lts
  name: assets
  when:
    ref:
    - refs/heads/main
    - refs/tags/**
- commands:
  - npm install > /dev/null
  - npx gulp default
  - npx gulp svg-sprite-list
  - mkdir exampleSite/themes/ && ln -s $(pwd)/ exampleSite/themes/hugo-geekdoc
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts
  name: assets-main
  when:
    ref:
    - refs/pull/**
- commands:
  - hugo -s exampleSite/
  image: thegeeklab/hugo:0.83.1
  name: build
- commands:
  - npm install -g js-beautify
  - html-beautify -r -f 'exampleSite/public/**/*.html'
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts-alpine
  name: beautify
- image: plugins/s3-sync
  name: publish
  settings:
    access_key:
      from_secret: s3_access_key
    bucket: geekdocs-root
    delete: true
    endpoint: https://sp.rknet.org
    path_style: true
    secret_key:
      from_secret: s3_secret_access_key
    source: exampleSite/public/
    strip_prefix: exampleSite/public/
  when:
    ref:
    - refs/heads/main
    - refs/tags/**
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
depends_on:
- test
- build
- docs
kind: pipeline
name: notifications
platform:
  arch: amd64
  os: linux
steps:
- image: plugins/matrix
  name: matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: 'Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name
      }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message:
      {{ build.message }}'
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  status:
  - success
  - failure
---
kind: signature
hmac: 09386d2160602d828eb53ed8eb3edf64983d43735652a1b038dff156a9f21709

...
