---
ci:
  collect:
    numberOfRuns: 3
    staticDistDir: exampleSite/public
    url:
      - http://localhost/
      - http://localhost/404.html
      - http://localhost/usage/getting-started/
    settings:
      chromeFlags: "--no-sandbox --headless --disable-dev-shm-usage"
      onlyCategories: ["performance", "accessibility", "best-practices", "seo"]
      skipAudits:
        [
          "color-contrast",
          "uses-long-cache-ttl",
          "csp-xss",
          "bf-cache",
          "is-crawlable",
          "image-size-responsive",
          "render-blocking-resources",
          "largest-contentful-paint",
          "unused-css-rules",
          "network-dependency-tree-insight",
          "legacy-javascript",
          "errors-in-console",
          "max-potential-fid",
          "interactive",
          "dom-size",
          "forced-reflow-insight"
        ]
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      color-contrast: off
      uses-long-cache-ttl: off
      csp-xss: off
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/14957
      bf-cache: off
      is-crawlable: off
      image-size-responsive: off
      render-blocking-resources: off
      largest-contentful-paint: off
      unused-css-rules: off
      network-dependency-tree-insight: off
      legacy-javascript: off
      errors-in-console: off
      max-potential-fid: off
      interactive: off
      dom-size: off
      forced-reflow-insight: off
      total-byte-weight: warn
      identical-links-same-purpose: warn
      tap-targets: warn
      unsized-images: warn
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/11460
      categories:performance:
        - warn
        - minScore: 0.95
      categories:accessibility:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 0.95
  upload:
    target: filesystem
    outputDir: lhci_reports
