---
ci:
  collect:
    numberOfRuns: 3
    psiStrategy: desktop
    staticDistDir: exampleSite/public
    url:
      - http://localhost/
      - http://localhost/404.html
      - http://localhost/posts/
    settings:
      chromeFlags: "--no-sandbox"
      throttling:
        cpuSlowdownMultiplier: "2.0"
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      uses-long-cache-ttl: off
      csp-xss: off
      tap-targets: warn
      unsized-images: warn
      image-size-responsive: warn
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/11460
      categories:performance:
        - warn
        - minScore: 0.95
      categories:accessibility:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 0.95
  upload:
    target: filesystem
    outputDir: lhci_reports
