---
ci:
  collect:
    numberOfRuns: 3
    staticDistDir: exampleSite/public
    url:
      - http://localhost/
      - http://localhost/404.html
      - http://localhost/usage/getting-started/
    settings:
      chromeFlags: "--no-sandbox"
      onlyCategories: ["performance", "accessibility", "best-practices", "seo"]
      skipAudits:
        [
          "color-contrast",
          "uses-long-cache-ttl",
          "csp-xss",
          "bf-cache",
          "is-crawlable",
          "image-size-responsive",
          "render-blocking-resources",
          "largest-contentful-paint"
        ]
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      color-contrast: off
      uses-long-cache-ttl: off
      csp-xss: off
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/14957
      bf-cache: off
      is-crawlable: off
      image-size-responsive: off
      render-blocking-resources: off
      largest-contentful-paint: off
      total-byte-weight: warn
      identical-links-same-purpose: warn
      tap-targets: warn
      unsized-images: warn
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/11460
      categories:performance:
        - warn
        - minScore: 0.95
      categories:accessibility:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 0.95
  upload:
    target: filesystem
    outputDir: lhci_reports
