+++
title = "Admonitions"
+++

:toc:
:toclevels: 2

{{< toc >}}

== Admonition types

There are certain statements you may want to draw attention to by taking them out of the content's flow and labeling them with a priority. These are called admonitions.

```tpl
[NOTE|TIP|IMPORTANT|CAUTION|WARNING]
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.
```

=== Example

[NOTE]
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.

[TIP]
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.

[IMPORTANT]
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.

[CAUTION]
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.

[WARNING]
====
Dolor sit, sumo unique argument um no. Gracie nominal id xiv. Romanesque acclimates investiture.
Ornateness bland it ex enc, est yeti am bongo detract re.

Romanesque acclimates investiture.
====

== Admonition icons

Icons can be added by setting a unicode glyph or a character reference to the `tip-caption` attribute:

```text
:tip-caption: 💡

[TIP]
It's possible to use Unicode glyphs as admonition icons.
```

```text
:tip-caption: pass:[&#128293;]

[TIP]
It's possible to use Unicode glyphs as admonition icons.
```

=== Example

:tip-caption: 💡

[TIP]
It's possible to use Unicode glyphs as admonition icons.


:tip-caption: pass:[&#128293;]

[TIP]
It's possible to use Unicode glyphs as admonition icons.
